# =============================================================================
# orchestrator/contracts.py
#
# Shared data contracts (dataclasses) for the entire orchestrator pipeline.
# Every stage — VLM, Planner, Critic, Executor, Reporter — exchanges typed
# objects defined here instead of raw dicts, keeping the codebase consistent.
#
# Key types (in pipeline order):
#   Evidence      — what the VLM extracted from the image
#   Plan          — the Planner's proposed execution plan
#   StepSpec      — a single tool-call step inside a Plan
#   ToolDecision  — the Critic's final tool selection
#   ToolResult    — output paths + success flag from a tool service
#   Trace         — full debug record of one pipeline run
#
# Helper functions at the bottom handle JSON serialisation and safe coercion
# of raw API response dicts into the typed dataclasses above.
# =============================================================================

from __future__ import annotations

from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Literal, Optional
import json
import time
import os

Modality = Literal["CT", "MRI", "PET", "XRAY", "US", "Unknown"]
Axis = Literal[0, 1, 2]  # 0=sagittal, 1=coronal, 2=axial


# -----------------------
# Core artifacts
# -----------------------

@dataclass
class Evidence:
    """What the VLM saw / extracted. Keep it model-agnostic."""
    modality: Modality = "Unknown"
    anatomy: List[str] = field(default_factory=list)        # e.g. ["lung", "heart"]
    pathology: List[str] = field(default_factory=list)      # e.g. ["infection", "effusion"]
    prompt_summary: str = ""                                 # brief natural-language summary
    spatial_hints: List[str] = field(default_factory=list)  # e.g. ["right lower lobe"]
    confidence: float = 0.0                                  # 0..1
    raw: Dict[str, Any] = field(default_factory=dict)       # optional: full model output


@dataclass
class StepSpec:
    """One tool-call step (tool + target + optional constraints)."""
    tool: str                                               # "totalseg" | "voxtell" | ...
    target: str                                             # what to segment
    within: Optional[str] = None                            # restrict within an anatomy
    params: Dict[str, Any] = field(default_factory=dict)


@dataclass
class Plan:
    """Proposed execution plan (can be generated by Hulu or LLM)."""
    modality: Modality = "Unknown"
    goal: str = ""                                          # e.g. "segment infection in lung"
    steps: List[StepSpec] = field(default_factory=list)
    notes: List[str] = field(default_factory=list)
    raw: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ToolDecision:
    """Critic's decision: select tool or request clarification."""
    tool: Optional[str] = None                              # None => cannot decide
    reason: str = ""
    required_inputs: List[str] = field(default_factory=list)  # e.g. ["text_prompt"]
    params: Dict[str, Any] = field(default_factory=dict)       # tool-specific params


@dataclass
class ToolResult:
    """Tool output paths + metadata."""
    tool: str
    ok: bool
    message: str = ""
    mask_path: Optional[str] = None                         # .nii.gz
    extra: Dict[str, Any] = field(default_factory=dict)


@dataclass
class Trace:
    """Everything we want to debug later."""
    run_id: str
    ts_unix: float
    input_path: str
    axis: Axis = 2
    num_slices: Optional[int] = None

    evidence: Optional[Evidence] = None
    plan: Optional[Plan] = None
    decision: Optional[ToolDecision] = None
    tool_result: Optional[ToolResult] = None

    warnings: List[str] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)
    timings: Dict[str, float] = field(default_factory=dict)  # stage -> seconds


# -----------------------
# Helpers
# -----------------------

def now_run_id(prefix: str = "run") -> str:
    """Generate a timestamped run ID string, e.g. 'run_20240610-143022'."""
    return f"{prefix}_{time.strftime('%Y%m%d-%H%M%S')}"


def to_json(obj: Any) -> str:
    """Serialise a dataclass or plain object to an indented JSON string."""
    if hasattr(obj, "__dataclass_fields__"):
        return json.dumps(asdict(obj), indent=2, ensure_ascii=False)
    return json.dumps(obj, indent=2, ensure_ascii=False)


def save_json(path: str, obj: Any) -> None:
    """Write a dataclass or plain object as JSON to *path*, creating dirs as needed."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(to_json(obj))


def load_json(path: str) -> Any:
    """Load and return parsed JSON from *path*."""
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


# -----------------------
# Safe coercion from dicts (API responses)
# -----------------------

def evidence_from_dict(d: Dict[str, Any]) -> Evidence:
    """Build an Evidence instance from a raw API response dict."""
    return Evidence(
        modality=d.get("modality", "Unknown"),
        anatomy=list(d.get("anatomy", []) or []),
        pathology=list(d.get("pathology", []) or []),
        prompt_summary=d.get("prompt_summary", "") or "",
        spatial_hints=list(d.get("spatial_hints", []) or []),
        confidence=float(d.get("confidence", 0.0) or 0.0),
        raw=d,
    )


def plan_from_dict(d: Dict[str, Any]) -> Plan:
    """Build a Plan instance (including its StepSpec list) from a raw dict."""
    steps = []
    for s in d.get("steps", []) or []:
        steps.append(
            StepSpec(
                tool=s.get("tool", ""),
                target=s.get("target", ""),
                within=s.get("within"),
                params=dict(s.get("params", {}) or {}),
            )
        )
    return Plan(
        modality=d.get("modality", "Unknown"),
        goal=d.get("goal", "") or "",
        steps=steps,
        notes=list(d.get("notes", []) or []),
        raw=d,
    )


def decision_from_dict(d: Dict[str, Any]) -> ToolDecision:
    """Build a ToolDecision from a raw dict, normalising empty/null tool values."""
    tool = d.get("tool", None)
    if tool in ["", "NONE", "null"]:
        tool = None
    return ToolDecision(
        tool=tool,
        reason=d.get("reason", "") or "",
        required_inputs=list(d.get("required_inputs", []) or []),
        params=dict(d.get("params", {}) or {}),
    )